### ISSUE TITLE
Missing list of options for theming

### ISSUE THREAD

**Issue by murbanowicz** [kzima/vuestrap-base-components#14]
Can you supply full list of possible options to theme components?

**Comment by kzima** [comment]
The full list of scss variables that u can use are available here: https://github.com/twbs/bootstrap/blob/v4-dev-rm-shrinkwrap-dep/scss/_variables.scss

It is just to many variables to play with and not everything can be styled with it, so some overrides are necessary. In the future release I am planning to remove theming option and allow for just overriding.
