### ISSUE TITLE
Add MULTIPLE support for dropdown select.

### ISSUE THREAD

**Issue by murbanowicz** [kzima/vuestrap-base-components#17]
Can you please add support for MULTIPLE for dropdown select?

**Comment by kzima** [comment]
I made this component a while ago but it is in different repo:

http://gritcode.github.io/gritcode-components/#/dropdown-multiselect

Is this something you were looking for?

**Comment by murbanowicz** [comment]
Great. Just suggestion - would be good to consolidate those components into one, current pack to reduce dependencies.

**Comment by kzima** [comment]
In the next version I am planning to actually split all the components into its own repos and make them completely independent, but in the same github organisation 'vue-components', similarly to https://github.com/PolymerElements.

I understand that having one dependency is very convenient and could be useful for prototyping, so as a solution I am planning to compile all components into one bundle repo called 'all-components'.

This way I will be able to version every single component and greatly simplify them. It will also work with any automation tool, including Browserfy. Something people are requesting from me all the time.

Does this sound good to you?

**Comment by murbanowicz** [comment]
Thank you. It sounds really good. Just please remember about "all-components"
