### ISSUE TITLE
Got Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by mehrancodes** [kzima/vuestrap-base-components#20]
Hey @kzima. After import it in my _main.js_ and running GULP it has no problem. but when I open the browser, it gives me that error. I even installed babel-loader but it still doesn't wrok!

**Comment by kzima** [comment]
you should use webpack with babel, 
here is a sample setup:
https://github.com/kzima/vuestrap-starter/blob/master/webpack.config.js
