### ISSUE TITLE
vuestrap-theme-loader

### ISSUE THREAD

**Issue by frabrunelle** [kzima/vuestrap-base-components#3]
Thank you for building these amazing components! :smiley: 

I am trying to integrate `vuestrap-base-components`. It seems like we also need to use `vuestrap-theme-loader`, but it's not documented in the README.md or http://kzima.github.io/vuestrap-base-components/#/.

It's in https://github.com/kzima/vuestrap-starter, but it would be nice if it was also mentioned in the documentation of `vuestrap-base-components`.

I might make a PR myself, but for now I'll just leave this issue open.

btw, I am using https://github.com/vuejs-templates/webpack-simple. It would be nice to have an example using that setup if possible :smile:

**Comment by kzima** [comment]
@frabrunelle thanks for your feedback :) I updated read.me and docs with some info about theming components.

To see [vuestrap-theme-loader](https://github.com/kzima/vueastrap-theme-loader) in action please visit [vuestrap-starter](https://github.com/kzima/vuestrap-starter). Its setup is slightly different to the [webpack-simple](https://github.com/vuejs-templates/webpack-simple) in a way that it does not use a vue-loader. Theme loader requires access to a raw scss file and it was just easier to not use vue-loader. Besides you gain a better syntax highlighting in sublime editor if you keep html, scss, and js in separate files :)

 I will keep this issue open for a while, but ideally I want to move any discussions to http://forum.vuejs.org/ and keep github issues for code related problems.

**Comment by frabrunelle** [comment]
Great! Thanks for updating the docs and the readme.

It would be nice to be able to use vuestrap-base-components with webpack-simple / vue-loader, but I guess the other approach used by vuestrap-starter works fine too :smile: 

I'll close this issue now. Cheers!
