### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by DaAwesomeP** [kzima/vuestrap-base-components#31]
Hi,
I'm trying to use vuestrap with Vue 2.0. However, the docs seem very out-of-date. For example, I'm trying to get the modal to work:
```vue
<b-button variant="primary" v-on:click="$emit('show::modal', 'modal1')">Open Modal</b-button>
<b-modal id="modal1" size="md" :fade="true">
   <div slot="modal-header">
    <h3>header</h3>
  </div>
  <div slot="modal-body">
    body
  </div>
  <div slot="modal-footer">
    <button class="btn btn-primary" v-on:click="$emit('hide::modal', 'modal1')">
      OK
    </button>
  </div>
</b-modal>
```
I caught on that `vs` needs to be replaced by `b` and that `$broadcast()` has been replaced by `emit()`, but what else is wrong? I couldn't get button groups to work either.

**Comment by kzima** [comment]
@DaAwesomeP it only works with vue 1.0, sorry

**Comment by DaAwesomeP** [comment]
@kzima Oh well. Thank you for informing me.
