### ISSUE TITLE
Support for $enable-flex

### ISSUE THREAD

**Issue by taylorzane** [kzima/vuestrap-base-components#4]
Hey Kris,

I found your project and I was wondering, do you ever plan to support using flex-box through the `$enable-flex` variable being set to `true` in `_variables.scss`?

**Comment by taylorzane** [comment]
I've gotta say, I really love this project. I figured out how to get `$enable-flex` working with a custom theme. My only reservation is...now I'm having to manually require all of the components that I want to use, which may not be a terrible thing...it would decrease bundle footprint if I only required what I needed. 

Is it possible to import all components `VuestrapBaseComponents = require 'vuestrap-base-components'` and use a custom theme?

Even if I had to do something like `VuestrapBaseComponents = require 'vuestrap-base-components/src/components/some-custom-theme-version'`, that would be fine.

If I have a custom theme file `app.scss`

``` sass
$enable-flex: true;
$body-bg: #0d4;
$brand-primary: #0af;
$btn-primary-color: #0af;
```

This will enable `$enable-flex` and `$body-bg: #0d4`, but it does not enable component-specific variables, since the components import their stylesheets in the component definition.

For now I'm going to manually require the components that I need.

**Comment by kzima** [comment]
Hi @taylorzane,

Yes you can import all components:

`import vuestrapBase from 'vuestrap-base-components/src/components'`

and then in your vue instance do this:

{
  ...
  components: vuestrapBase,
  ...
}

Just bear in mind that in this case you wiil have to use `vs` prefix, like so `<vs-alert>`. See this file https://github.com/kzima/vuestrap-base-components/blob/master/src/components/index.js

**Comment by taylorzane** [comment]
Interesting...I just tried that and now my custom variables are working just fine. I'm not sure what I was doing wrong. Keep up the good work Kris!
